var billDetailLang = {
    "zh": {//中文简体
        pageTitle: "单据详情",
        pageContent: {
            documentWholeLabel: "单据全貌",
            enclosureLabel: "附件",
            flowChartLabel: "流程图",
            associatedForm:"关联表单",
            zhenWenLabel: "正文",
            assignToLabel: "指派给:",
            cancelLabel: "取消",
            aprovalLabel: "批准",
            optionLabel: "搜索",
            determineLabel: "确定",
            budgetCtrlTitle: "预算控制"
        },
        pagePlaceHoder: {

            assign_text: "请在此处输入内容",
            search_text: "搜索"

        },
        pageMessage: {
            neverEnterMobileApprove: "首次使用，请通过应用->移动审批进入后启用消息功能",
            detailfailedLoad: "单据详情信息加载失败",
            editdetailfailedLoad: "单据编辑列表信息加载失败",
            inquirefailedLoad: "查询动作列表加载失败",
            assignToLabel: "指派给:",
            assignPersonLabel: "请选择指派对象",
            refusalToLabel: "驳回给:",
            refusalPersonLabel: "请选择驳回对象",
            reassignmentToLabel: "改派给",
            reassignmentPersonLabel: "请选择改派人员",
            addPersonLabel: "请选择加签人",
            contactsToLabel: "联系人:",
            historyfailedLoad: "审批历史加载失败",
            submitLabelInfo: "提交人",
            accessory: "附件",
            designeeListfailed: "指派人员列表加载失败",
            noFingerSentInfo: "无指派人",
            noFeeInfo: "鉴权失败",
            networkfailedInfo: "网络连接失败，请您检查网络后重试",
            notAuthedInfo: "您使用的是免费版本，无法使用审批功能，若要进行审批操作，请联系管理员",
            approveByQyjInfo: "来自移动端",
            approveByQyMInfo: "来自移动+",
            cancelLabel: "取消",
            personNoInformation: "此人员无任何信息",
            failure: "执行函数失败",
            rowInfo: "条目",
            personInfo: "人员信息",
            closeIncogMode: "请关闭手机无痕模式进行浏览",
            resultNull: "接口返回为null",
            actionFailed: '操作失败',
            getMafailure: "取得MA地址失败",
            assignInputLabel: "请输入审批意见",
            assignMustInputLabel: "批语不能为空,请输入",
            unallowedApprove: "此时不能进行审批",
            redirectError: "单据列表加载失败",
            budgetCtrl: "超出预算控制，是否继续操作？"
        }
    },
    "en": {//英文
        pageTitle: "Bill details",
        pageContent: {
            documentWholeLabel: "Billtable",
            enclosureLabel: "Attachment",
            flowChartLabel: "Flowchart ",
            assignToLabel: "Assigned to",
            cancelLabel: "Cancel",
            aprovalLabel: "Approve",
            optionLabel: "Search",
            determineLabel: "OK",
            budgetCtrlTitle: "Budget Control"
        },
        pagePlaceHoder: {
            assign_text: "Please input the content here",
            search_text: "Search"
        },
        pageMessage: {
            neverEnterMobileApprove: "Please enter Mobile Approve that locate in Apps first to enable this function",
            detailfailedLoad: "Failed to load documents in Detail",
            editdetailfailedLoad: "Failed to load documents in the edited list",
            inquirefailedLoad: "Query action list failed to load",
            assignToLabel: "Assigned to:",
            assignPersonLabel: "Please select person to assign",
            refusalToLabel: "Refusal to:",
            refusalPersonLabel: "Please select person to refusal",
            reassignmentToLabel: "Reassignment to",
            reassignmentPersonLabel: "Please select person to reassignment",
            addPersonLabel: "Please select person to add",
            contactsToLabel: "Contact:",
            historyfailedLoad: "Approval History failed to load",
            submitLabelInfo: "Submitter",
            accessory: "Attachment",
            designeeListfailed: "Designee list fails to load",
            noFingerSentInfo: "No designated person",
            noFeeInfo: "Your mobile approval is overdue,please contact the administrator.",
            networkfailedInfo: "Please check your network setting and try again",
            notAuthedInfo: "You are using a free version, approval function, if you want to, please contact the administrator.",
            approveByQyjInfo: "from Company+",
            approveByQyMInfo: "from Mobile+",
            cancelLabel: "Cancel",
            personNoInformation: "This person has no information",
            failure: "Error",
            rowInfo: "item",
            personInfo: "Person Info",
            closeIncogMode: "Please close the Incognito Mode of browser",
            resultNull: "result is null",
            actionFailed: 'action failed',
            getMafailure: "Failed to get MA address",
            assignInputLabel: "Please enter comments",
            assignMustInputLabel: "Comments can not be empty. Please enter",
            unallowedApprove: "can not approve now",
            redirectError: "Failed to load bills list",
            budgetCtrl: "Over budget control. Continue?"
        }
    },
    "tw": {//中文繁体
        pageTitle: "單據詳情",
        pageContent: {
            documentWholeLabel: "單據全貌",
            enclosureLabel: "附件",
            flowChartLabel: "流程圖",
            assignToLabel: "指派給:",
            cancelLabel: "取消",
            aprovalLabel: "批准",
            optionLabel: "搜索",
            determineLabel: "確定",
            budgetCtrlTitle: "預算控制"
        },
        pagePlaceHoder: {

            assign_text: "請在此處輸入內容",
            search_text: "搜索"

        },
        pageMessage: {
            neverEnterMobileApprove: "首次使用，請通過應用->移動審批進入後啟用消息功能",
            detailfailedLoad: "單據詳情信息加載失敗",
            editdetailfailedLoad: "單據編輯列表加載失敗",
            inquirefailedLoad: "查詢動作列表加載失敗",
            assignToLabel: "指派給:",
            assignPersonLabel: "請選擇指派對象",
            refusalToLabel: "駁回給:",
            refusalPersonLabel: "請選擇駁回對象",
            reassignmentToLabel: "改派給",
            reassignmentPersonLabel: "請選擇改派人員",
            addPersonLabel: "請選擇加簽人",
            contactsToLabel: "聯系人:",
            historyfailedLoad: "審批歷史加載失敗",
            submitLabelInfo: "提交人",
            accessory: "附件",
            designeeListfailed: "指派人員列表加載失敗",
            noFingerSentInfo: "無指派人",
            noFeeInfo: "運營健全失敗",
            networkfailedInfo: "網絡連接失敗，請您檢查網絡後重試",
            notAuthedInfo: "您使用的是免費版本，無法使用審批功能，若要進行審批操作，請聯系管理員",
            approveByQyjInfo: "來自移動端",
            approveByQyMInfo: "來自移動+",
            cancelLabel: "取消",
            personNoInformation: "此人員無任何信息",
            failure: "執行函數失敗",
            rowInfo: "條目",
            personInfo: "人員信息",
            closeIncogMode: "請關閉手機無痕模式進行瀏覽",
            resultNull: "接口返回為null",
            actionFailed: '操作失敗',
            getMafailure: "取得MA地址失敗",
            assignInputLabel: "請輸入審批意見",
            assignMustInputLabel: "批語不能為空,請輸入",
            unallowedApprove: "此時不能進行審批",
            redirectError: "單據列表加載失敗",
            budgetCtrl: "超出預算控制，是否繼續操作？"
        }
    }
}
